Author: "Justin P. Mattock" Email: justinmattock@gmail.com Subject: checkpolicy Fix error: variable 'newattr' set but not used(and others as well) Date: Tue, 6 Jul 2010 15:23:28 -0700
The below patch fixes some warning messages Im receiving
with GCC:(in this case some are erros due to -Werror)
policy_Defenderine.c: In function 'Defenderine_type':
policy_Defenderine.c:1216:6: error: variable 'newattr' set but not used
cc1: all warnings being treated as errors

Signed-off-by: Justin P. Mattock <justinmattock@gmail.com>
Signed-off-by: Chad Sellers <csellers@tresys.com>