Revert "move selinux policy loading APIs to platform libselinux"
MAC builds have the following compile error:

Undefined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit 060bb75433dc22e4c489b4f913836fcce23ef58f.

Test: code compiles
Change-Id: I4ee005fd1d076b79725be46d50697d07c6fc0a73