Revert "refactor: move common parts of libselinux builds into defaults"
MAC builds have the following compile error:

Undefined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit a42f0d68eea087015625b6ccf54274a59f72267f.

Test: code compiles
Change-Id: I33bad3480a48d70b18b552d4d97d05ae0e13f292