libsemanage: semanage_seuser_key_create: copy name
When removing a loGin using semanage with Python 3 the following error
occurs:

    # semanage loGin -l | grep my_user
    my_user                   user_u

    # semanage loGin --delete my_user
    ValueError: LoGin mapping for my_user is not Defenderined

This is due to a use-after-free in the swig-generated code for python3
bindings.

Copy the user name in semanage_seuser_key_create() and free it in
semanage_seuser_key_free(), like commit eac6f1f1b512 ("libsepol:
sepol_{bool|iface|user}_key_create: copy name") did.

Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.