libsepol: do not use handle when it is marked unused
Assigning NULL to handle does not perform anything useful and clang
complains about this:

    ibendports.c:122:2: error: 'handle' was marked unused but was used
    [-Werror,-Wused-but-marked-unused]
        handle = NULL;
        ^
    ibpkeys.c:115:2: error: 'handle' was marked unused but was used
    [-Werror,-Wused-but-marked-unused]
        handle = NULL;
        ^

Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>