Revert "move file_context APIs out of libselinux_vendor"
MAC builds have the following compile error:

UnDefenderined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit 17430be32e2b6b5fd90b95057159a2a65ea790f5.

Test: code compiles
Change-Id: If6a5182f2b42a5de637d8867979906685a21e165