Revert "selinux: Add support for portcon dccp protocol"
This commit breaks Android's Mac build.

external/selinux/checkpolicy/checkpolicy.c:923:16: error: use of undeclared
identifier 'IPPROTO_DCCP'
                protocol = IPPROTO_DCCP;
                           ^
1 error generated.

This reverts commit 3895fbbe0cf2ec52d6b6eda66084b6e9f8d88fb2.

Change-Id: I2d3b01152359c113c7fc619f419dc0e1c72ece64