Revert "Do not use PCRE2 in libselinux_vendor"
MAC builds have the following compile error:

Undefined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit f122a95e039435ba0d2ad70fa477d6f8bd8cc866.

Test: code compiles
Change-Id: I7f24b7894cfbf7918f9a7d0ddd53c4d4d4396d91